### ISSUE TITLE
Alter send to all to not send to new players

### ISSUE THREAD

**Issue by RoboMWM** [ucchyocean/UndineMailer#63]
Currently, it seems if I send a message to all players, new players who join the server receive these messages as well. I haven't confirmed this yet, but looking at the logs makes this appear to be the case.

**Comment by ucchyocean** [comment]
I think, this is needed, but this feature should not be such as switchable.
You have sent some "All" mails, and if you alter "not send to new players", "All" mails will cannot be read. Because these mails were not recoreded "To" players.

OK, I want to add new special groups.
- All - Specail group that all connected players including new comers.
- AllConnected - Special group that all connected players without new comers.
- AllLogin - Special group that all connecting players.

How about this idea?

**Comment by ucchyocean** [comment]
Fixed
![2015-09-12_16 07 32](https://cloud.githubusercontent.com/assets/2563444/9830465/098de2d6-596a-11e5-8ed9-c36e92fe4f56.png)
![2015-09-12_16 12 32](https://cloud.githubusercontent.com/assets/2563444/9830466/0f2a50c6-596a-11e5-9cbe-1014e4793616.png)
