### ISSUE TITLE
Make line-names translatable

### ISSUE THREAD

**Issue by Androkai** [ucchyocean/UndineMailer#90]
Most of my new players have problems with writing mails. It feels like they don't understand how to write text to a mail. Can you make the line-names `M1`, `M2`, `M3` and so on translatable so I can change it to something more intuitive like `Click me to add a message to line 1!`?

**Comment by RoboMWM** [comment]
The hover messages are translatable.

**Comment by Androkai** [comment]
I know but it seems like my users never come to the point where hovering-tips help.

**Comment by ucchyocean** [comment]
Hi Androkai,

OK, I could understand your request.
I will change the following point to be translatable.
https://github.com/ucchyocean/UndineMailer/blob/a693527038fb57d68362958f1c8b27b0a87b0d6a/src/main/java/org/bitbucket/ucchy/undine/MailManager.java#L1159

But I feel this change is not the best solution, because this line is too narrow to edit the message.
We have to think annother solution for this issue in the future version.

**Comment by RoboMWM** [comment]
Perhaps when the user enters the /mail write mode, it could say "Click the [M1] to edit this line!" or similar.

**Comment by ucchyocean** [comment]
@RoboMWM 
Nice idea! I will think about that.

**Comment by ucchyocean** [comment]
Fixed.

TIPS message will be shown when all message lines are empty.

JP:
![2016-10-23_22 05 00](https://cloud.githubusercontent.com/assets/2563444/19626454/ac3752da-996d-11e6-8a62-6f88e882818c.png)

EN:
![2016-10-23_22 06 01](https://cloud.githubusercontent.com/assets/2563444/19626457/ba6e7f04-996d-11e6-8cb6-dfc825efd8ca.png)

DE:
![2016-10-23_22 06 45](https://cloud.githubusercontent.com/assets/2563444/19626458/c0994f26-996d-11e6-9c7f-d5f18031d9b3.png)

**Comment by Androkai** [comment]
Thx :)
